### ISSUE TITLE
Question: faster listview?

### ISSUE THREAD

**Issue by juh9870** [fuqunaga/RosettaUI#10]
Currently, when using lists, the whole list is generated at once, aka all of its elements are added to the tree, which may cause issues if there are a lot of elements, so my question:
Is there a UI element that allows me to create a list that only shows elements that are currently on-screen? Afaik, UI toolkit default ListView already have this functionality, so would it be possible to have a similar feature here? Maybe as a separate component even

**Comment by fuqunaga** [comment]
The functionality of UIToolkit's ListView only works when each element has the same height.
RosettaUI does not use this feature because it works at different heights.

ScrollView also has the same problem , so I will try to solve it eventually.

**Comment by fuqunaga** [comment]
RosettaUI.UIToolkit 1.1.0 now supports list item virtualization🎉
ScrollView is not supported at this time because it would be too much work.

**Comment by juh9870** [comment]
Cool! Are there examples of it?

**Comment by fuqunaga** [comment]
UI.List() will always have this behavior.

**Comment by fuqunaga** [comment]
It supports elements of different sizes!
However, UIToolkit's ListView is buggy, so I recommend using the latest version of Unity 2021 or 2022.

**Comment by juh9870** [comment]
Great! This is excellent, then. Does it also means that RosettaUI now supports unity 2022?

**Comment by fuqunaga** [comment]
Yes:thumbsup:
