### ISSUE TITLE
Float values limited?

### ISSUE THREAD

**Issue by SilentGamzee** [fuqunaga/RosettaUI#2]
Changing float values ​​seems to be limited to [-0.02f; 0.02f] when changing by holding down the mouse button.
Unity 2021.3.2f1
Rosetta UI 0.0.2 (last version from Package Manager)

P.s. In general, the framework looks very good, thank you very much)

**Comment by fuqunaga** [comment]
Is it the action of dragging a label?
It is [UIToolkit's FloatField](https://docs.unity3d.com/Packages/com.unity.ui@1.0/api/UnityEditor.UIElements.FloatField.html) and behaves similarly to the Unity Inspector.
You can also change the step width by holding down Shift/Ctrl.

Thank you for your report😀

**Comment by SilentGamzee** [comment]
Example. I increase the `float` value to the right, but the value does not become more than 0.2f. Looks weird and uncomfortable.
Is this a UIToolkit problem? Everything is fine with `int` fields
https://user-images.githubusercontent.com/25285476/169289915-68ea6be9-a9b6-468a-868c-32fcd9be1d37.mp4

**Comment by fuqunaga** [comment]
Thank you for the movie.

I could not reproduce it in my environment.
![check2](https://user-images.githubusercontent.com/821072/169458197-9a247bf7-f442-47c4-aa9b-b8ec1436618d.gif)

I don't know the cause of the problem, so I need some information.
If possible, please try the latest version (RosettaUI 0.2.2) or another environment.
If you always have the same problem, please send me a sample project and I will try to reproduce it.

**Comment by fuqunaga** [comment]
Try a different PC or OS if possible.
I tried it on my M1 Macbook Air and the UIToolkit dragging did not work correctly (but it seems not the same issue).
It worked correctly on Windows.

**Comment by SilentGamzee** [comment]
I made a build (version 0.2.2. Unity version 2021.2.8f), tried to run it on two more PCs, the bug remained. Tried only Windows

**Comment by fuqunaga** [comment]
I'm sorry, but I can't figure out what's causing this.
If you have any information to reproduce it on my end, please let me know.

**Comment by SilentGamzee** [comment]
Later, when I finish the tasks for my project, I will try to find the causes of this problem and fix it locally. I'll post here if I find a solution.

**Comment by juh9870** [comment]
I have the same issueI have the same issue
I was going through all the examples one by one, and first noticed this at `MethodExample`, came back to older ones and error is still here
https://user-images.githubusercontent.com/15922601/192898528-cae4756f-d170-4fe3-bad1-9e40636f9440.mp4

**Comment by juh9870** [comment]
I've figured out this issue. The cause is that `StringToValue` method uses `EditorGUI.StringToDouble`, which in turn uses `double.TryParse` without specifying explict culture, so if default system culture formats floats not like 9.5, but for example 9,5 it bugs out

**Comment by juh9870** [comment]
The same issue causes #4
