### ISSUE TITLE
Unity 2023.2 compatibility

### ISSUE THREAD

**Issue by jkelin** [fuqunaga/RosettaUI#25]
I'm getting console full of errors in unity 2023.2

- RosettaUI 1.5.1
- RosettaUI - UI Toolkit 1.4.1

![image](https://github.com/fuqunaga/RosettaUI/assets/2418383/b2b096cf-d48d-43d7-b367-7a7ef904e098)

**Comment by fuqunaga** [comment]
We have added support for Unity 6🎉
 These versions should also work with Unity 2023.

* RosettaUI 1.7.1
* RosettaUI - UI Toolkit 1.6.0

[6ef3967](https://github.com/fuqunaga/RosettaUI/commit/6ef39674f881a514a6213398fff1a331a8ed06f7)
