### ISSUE TITLE
 'IPopupMenuImplement' could not be found on RosettaUI - UI Toolkit ver.  1.7.0

### ISSUE THREAD

**Issue by nobnak** [fuqunaga/RosettaUI#29]
If you install Rosseta UI ver. 1.7.0, you'll encounter following error:

> Library\PackageCache\ga.fuquna.rosettaui.uitoolkit@1.7.0\Runtime\VisualElement\Utilities\PopupMenuUtility.cs(9,39): error CS0246: The type or namespace name 'IPopupMenuImplement' could not be found (are you missing a using directive or an assembly reference?)

[Reproducible project](https://github.com/nobnak/test-rosetta)

**Comment by nobnak** [comment]
![スクリーンショット 2024-09-14 180044](https://github.com/user-attachments/assets/54b61de5-7376-4b78-a6d0-3ecc7594fb8b)

**Comment by fuqunaga** [comment]
Sorry, the version of RosettaUI specified by RosettaUI-UIToolkit may be wrong.
If you manually increase the version of RosettaUI, it should work.

![image](https://github.com/user-attachments/assets/522e9880-84e6-4c49-879b-ea1d2bed9da8)
