### ISSUE TITLE
Detecting if the mouse is on or interacting with the UI

### ISSUE THREAD

**Issue by Ryan-Red** [fuqunaga/RosettaUI#30]
Hi,
I've been using RosettaUI for about 3 months now on my project and love it, its very convenient. I've recently been having some trouble with scrolling and moving my UI, as doing so doesn't "block" the mouse input from also interacting with the rest of my game. 

I was wondering if theres a way to check if the mouse is either on or interacting with the UI, that way I can skip those inputs. Maybe there's a better way to solve my problem?

Thanks!

**Comment by fuqunaga** [comment]
You can handle it by using the New Input System to separate the game's and UI's inputs on the application side, so please give that a try.
I have also been concerned about this and investigated it before, but it seems there is no generic method that can be implemented on the library side.

Thank you for using this library.

**Comment by Ryan-Red** [comment]
Thanks! I managed to implement the new Input system and added in some checks to detect if the cursor is over the UI element and then switching the action maps, it seems to do the job!

Thanks again!
