### ISSUE TITLE
Dragging windows tank performance 

### ISSUE THREAD

**Issue by juh9870** [fuqunaga/RosettaUI#5]
Dragging windows with a lot of fields cause constant layout recalculation (at least this is what I suspect based on profiler), dropping FPS from 300 to 10. I've used example scene windows to test it

Same thing happens when I'm rearranging array items by dragging them, which causes even worse performance drops, down to 5.

**Comment by fuqunaga** [comment]
Thanks for the info!

I'm aware of the issue.
I haven't come up with a good way to suppress UIToolkit's layout calculations while maintaining the auto-layout functionality.

As a workaround, fixing the size of the Element in smaller units (Element.SetWith()/SetHeight()) may improve performance.

**Comment by juh9870** [comment]
Okay, I will try. And what about lists dragging? should I create a separate issue for that, or are they similar enough?

**Comment by fuqunaga** [comment]
If it's also happening with the example in this repository, please make it a separate issue.
It may depend on an environment like #2.
